theme: "hugo-PaperMod"
baseURL: https://louislippens.netlify.app/
languageCode: en-uk
title: Louis Lippens
paginate: 5
googleAnalytics: G-353SE2Q1DW

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

permalinks:
  post: /:year/:month/:day/:slug/

menu:
  main:
    - name: home
      url: /
      weight: 1
    - name: about
      url: /about/
      weight: 2
    - name: cortest
      url: /cortest/
      weight: 3
      
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Louis Lippens
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  homeInfoParams:
      Title: "Hello, visitor \U0001F44B"
      Content: >
        Welcome to my personal web space. Have a look around. You can read more about me in the eponymous tab.
        I don't blog often, but when I do, you will find it here.
        Besides, you can can discover my work and a few of my highlighted projects in the other tabs above.
  socialIcons:
      - name: "twitter"
        url: "https://twitter.com/LippensLouis"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/louislippens/"
  assets:
        favicon: "/favicon.ico"
        favicon16x16:  "/favicon-16x16.png"
        favicon32x32:  "/favicon-32x32.png"
        apple_touch_icon:  "/apple-touch-icon.png"

markup:
  goldmark:
    renderer:
      unsafe: true
