<<<<<<< HEAD
[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.85.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
=======
[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.85.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
>>>>>>> 5df9bc554174fd97f8de5bd48a25b35e12803f2e
